wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.6.9
    start_time: 1670601736.277243
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.6.9
      5: 0.13.4
      8:
      - 2
      - 5
batch_size:
  desc: null
  value: 64
episodes:
  desc: null
  value: 5
lr:
  desc: null
  value: 0.0001
name:
  desc: null
  value: ddqn
